MAPC/massbuilds

- ember/app/components/login-subpanel.js
- ember/app/components/password-reset-subpanel.js
- ember/app/components/signup-subpanel.js
- ember/app/controllers/map.js
- ember/app/styles/components/user-subpanels.scss
- ember/app/templates/components/login-subpanel.hbs
- ember/app/templates/components/password-reset-subpanel.hbs
- ember/app/templates/components/user-panel.hbs
- ember/tests/integration/components/password-reset-subpanel-test.js
- rails/Gemfile
- rails/Gemfile.lock
- rails/app/controllers/password_resets_controller.rb
- rails/app/mailers/application_mailer.rb
- rails/app/mailers/user_mailer.rb
- rails/config/environments/production.rb
- rails/config/environments/staging.rb
- rails/config/secrets.yml
Currently working towards getting a working password reset function. This still has a couple issues:
```
[13] pry(#<PasswordResetsController>)> request.params
=> {"controller"=>"password_resets", "action"=>"create"}
```
> 65 password resets

- ember/app/templates/glossary.hbs
This resolves #10 by providing the content for the glossary.
> [WIP] Resolve #10 Provide Terms/Glossary for Data

- ember/ember-cli-build.js
- ember/package-lock.json
- ember/package.json
Partially resolves #103. The page will at least load now. There are still styling issues on IE.
> Partially resolve IE compatibility by including babel-polyfill

- .dockerignore
- docker-compose.yml
- ember/.dockerignore
- ember/Dockerfile
- ember/app/styles/components/map-legend.scss
- ember/app/styles/routes/map.scss
- ember/app/templates/map.hbs
- ember/package-lock.json
- rails/.dockerignore
- rails/Dockerfile
- rails/config/database.yml
> Add links to sub pages

- rails/app/controllers/developments_controller.rb
- rails/app/controllers/users_controller.rb
- rails/app/serializers/development_serializer.rb
- rails/app/serializers/full_development_serializer.rb
- rails/config/database.yml
> Fix development relationships in user serialization

- ember/app/components/metric-filter-subpanel.js
- ember/app/controllers/map.js
> Fix filter subgroups

- ember/app/templates/faq.hbs
Update FAQ text to eliminate a typo and reflect the fact we do not use only blue dots anymore.
> Resolve #102 FAQ Text Update

- ember/app/components/mapbox-map.js
- ember/app/controllers/map.js
- ember/app/services/map.js
- ember/app/styles/routes/map.scss
- ember/app/templates/map.hbs
- rails/config/database.yml
> Add satellite basemap and button zoom

- rails/app/models/development.rb
This resolves #40 by updating the loc_id value to the relevant value from the parcels database when saving a new development.
> Resolve #40 Update loc_id on Saving New Devel

- ember/app/components/mapbox-map.js
> Fix error causing the create form from not opening when data is filtered

- ember/app/models/development.js
- ember/app/templates/components/development-form.hbs
- ember/app/utils/filters.js
- rails/db/migrate/20180625194837_remove_estemp_from_developments.rb
- rails/db/schema.rb
This resolves #99 by removing the estimated employment values from the interface and app.
> Resolve #99 Remove Estimated Employment Values

- ember/app/content.js
> Adds parcel fiscal year definition

- ember/app/templates/map/developments/development/index.hbs
- rails/app/controllers/developments_controller.rb
- rails/app/models/edit.rb
- rails/app/serializers/full_development_serializer.rb
- rails/app/views/developments/_form.html.erb
- rails/app/views/developments/index.html.erb
- rails/app/views/developments/show.html.erb
- rails/lib/tasks/import.rake
- rails/spec/factories/developments.rb
> Remove estemp everywhere

- ember/app/components/mapbox-map.js
> Fix incorrect function name from rebase

- ember/app/components/mapbox-map.js
- ember/app/services/map.js
Remove a development from the map when it's deleted. Resolves #152
> Delete development from map

- ember/app/controllers/map.js
- ember/app/styles/components/filter-panel.scss
- ember/app/styles/modules/left-panel-links.scss
- ember/app/templates/components/filter-panel.hbs
- ember/app/templates/map.hbs
Resolves #154 and resolves #153
> Change searchbar placeholder and add close button to filter panel

- .gitignore
- ember/app/components/mapbox-map.js
> Remove event handlers on map destruction

- ember/app/components/mapbox-map.js
- ember/app/utils/paint-properties.js
Resolves #149 
This PR also suggests a styling change to the developments in satellite view.
> Highlight development being viewed

- ember/app/styles/modules/hamburger.scss
- ember/app/templates/map.hbs
When the right panel is showing, the hamburger now animates into it's active state which changes the hamburger into an X.
Resolves #120
> Implement animated hamburger active state

- ember/app/components/goto-bar.js
> Use Pelias over SSL

- ember/app/utils/filters.js
- ember/app/utils/status-colors.js
> Remove 'deselected' status option

- ember/app/components/mapbox-map.js
- ember/app/styles/components/map-legend.scss
- ember/app/styles/routes/map.scss
- ember/app/templates/map.hbs
> Link legend wrapper to left panel

- rails/Gemfile
- rails/Gemfile.lock
- rails/app/models/development.rb
- rails/lib/tasks/database.rake
This will slightly speed up development creation, so I figure we should merge this in before Wednesday.
> Remove subqueries from calculated fields

- ember/app/components/share-buttons.js
- ember/app/styles/components/search-bar.scss
- ember/app/styles/components/share-buttons.scss
- ember/app/styles/routes/map.scss
- ember/app/templates/components/search-bar.hbs
- ember/app/templates/components/share-buttons.hbs
- ember/app/templates/map.hbs
Resolves #137 and resolves #121. This PR moves the download buttons to below the menu toggler and highlights when filters are active.
> Move download buttons and highlight active filters

- rails/README.md
- rails/app/models/development.rb
- rails/lib/tasks/database.rake
> Recalculate calculated fields on edit

- ember/app/components/mapbox-map.js
- ember/app/components/share-buttons.js
- ember/app/styles/components/development-form.scss
- ember/app/styles/components/search-bar.scss
- ember/app/styles/components/share-buttons.scss
- ember/app/styles/partials/_mixins.scss
- ember/app/styles/routes/map.scss
- ember/app/styles/routes/map/developments/development.scss
- ember/app/templates/components/development-form.hbs
- ember/app/templates/components/share-buttons.hbs
- ember/app/templates/map.hbs
- ember/app/templates/map/developments/development/index.hbs
For users with smaller screens (or half screens), the left panel has been prohibitively large such that it obscures the map. While MassBuilds is by no means a mobile friendly application yet, this PR attempts to make the left panel sizing more user friendly.
> Make the left panel more responsive

- rails/Gemfile
- rails/Gemfile.lock
- rails/app/models/development.rb
- rails/app/models/edit.rb
- rails/db/migrate/20180710142821_add_deleted_at_to_developments.rb
- rails/db/migrate/20180710164947_add_deleted_at_to_edits.rb
- rails/db/schema.rb
Resolves #179 but requires #160
> Prevents complete deletion of developments and links edits

- ember/app/components/development-form.js
- ember/app/styles/components/development-form.scss
- ember/app/styles/partials/_vars.scss
- ember/app/templates/components/development-form.hbs
Invalid fields are now highlighted. @arouault does this resolve #183?
> Visible validations

- ember/app/controllers/map/developments/for/user.js
> Ensure recomputation of the my developments list

- ember/app/content.js
- ember/app/styles/modules/table.scss
- ember/app/templates/components/development-form.hbs
- ember/app/templates/map/developments/development/index.hbs
- ember/app/utils/filters.js
> Break out housing unit definitions

- ember/app/styles/components/mapbox-map.scss
- ember/app/styles/components/share-buttons.scss
- ember/app/styles/components/user-subpanels.scss
- ember/app/styles/partials/_reset.scss
- ember/app/styles/routes/map.scss
Mapbox and OSM attributions are respectful (and required).
> Fix Mapbox attributions

- rails/app/models/development.rb
Merging as simple hotfix to add port to pgsql2shp command.
> Add port to pgsql2shp command

- ember/app/components/development-form.js
- ember/app/controllers/map/developments/create.js
- ember/app/styles/components/development-form.scss
- ember/app/templates/components/development-form.hbs
- ember/app/templates/map/developments/create.hbs
- ember/app/templates/map/developments/development/edit.hbs
- ember/package-lock.json
- ember/package.json
Resolves #194.
Validations for composite fields have been confusing in the past.
> Implement Eric's validation design for composite values

- ember/app/components/development-form.js
Resolves no particular issue.
This is a small refactor to make the development form properties follow DRY principles.
> Apply dry principles to column names in development form

- ember/app/components/development-form.js
- ember/app/styles/components/discrete-filter-subpanel.scss
- ember/app/styles/components/filter-panel.scss
- ember/app/styles/components/map-legend.scss
- ember/app/styles/components/metric-filter-subpanel.scss
- ember/app/styles/components/search-bar.scss
- ember/app/styles/components/share-buttons.scss
- ember/app/styles/components/user-subpanels.scss
- ember/app/styles/components/welcome-modal.scss
- ember/app/styles/partials/_vars.scss
- ember/app/styles/routes/map.scss
- ember/app/templates/components/login-subpanel.hbs
- ember/app/templates/components/signup-subpanel.hbs
- ember/app/templates/map.hbs
Resolves IE compatibility issues.
IE handles flex basis very differently than Chrome does.
> Fix IE compatibility and form autofill for res and comm only devs

- ember/app/index.html
- ember/app/router.js
We want to track usage of the site.
> Add google analytics to ember

- ember/app/components/development-form.js
- rails/config/environments/production.rb
- Fix validations for summed values equal to 0
> Version 1.0.8

- ember/app/components/development-form.js
- rails/app/models/development.rb
- rails/app/policies/development_policy.rb
- Geocode in municipal permissions policy for new developments
> Version 1.0.9

- rails/db/migrate/20201130212232_migrate_flag_data.rb
- rails/db/schema.rb
* In order to allow Josh to review current flags, we create this migration to import flags from the old system into the new one.
> Migrate Flags

- rails/Gemfile.lock
* Bump dependencies for security reasons.
> Bump dependencies
