MAPC/massbuilds

- ember/app/router.js
- ember/app/routes/faq.js
- ember/app/styles/routes/_all.scss
- ember/app/styles/routes/faq.scss
- ember/app/templates/faq.hbs
This resolves #84 by adding a FAQ page to MassBuilds accessible at /faq. It just needs to be linked from somewhere and should maybe be double checked for styling.
> Resolve #84

- rails/app/models/development.rb
This fixes the CSV download by replacing all zip codes with a quoted version of them so that Microsoft Excel will not munge the leading zeros.
It also refactors the syntax of the CSV generation to no longer uselessly gsub commas into semicolons in the attribute names.
> Fix CSV Download

- rails/app/models/development.rb
Turns out, we misspelled the column we wanted to remove because these column names have inconsistent abbreviation patterns.
Resolves #100
> Fix column typo to remove correct d_n_trnsit column

- ember/app/components/mapbox-map.js
- ember/app/templates/components/search-bar.hbs
Resolves #125. This removes the unnecessary onClick from the search bar menu which takes the user to the new development page. The onClick had been adding an undefined filter parameter which triggered the map to refocus.
> Prevent zoom when entering the create dev screen from the searchbar

- ember/app/components/mapbox-map.js
- ember/app/routes/map/developments/create.js
- ember/app/routes/map/developments/development/edit.js
- rails/app/models/development.rb
- rails/app/models/edit.rb
Resolves #143 (mostly). This PR extends location editing to the development edit panel, however, as #143 suggested, this iteration does not include a safeguard to prevent a user from accidentally moving the location. A user would have to "cancel" their edits to undo an accidental location nudge.
> Edit development location

- ember/app/components/search-bar.js
This PR resolves #93 by checking query words against keywords instead of matching the string from start to finish. This means that you can type 'riv' and get 'Fall River' where before you would have to type 'fal' to get that same result.
> Improve search-bar algorithm via keywords

- ember/app/components/development-form.js
- ember/app/controllers/map/developments/create.js
- ember/app/models/development.js
- ember/app/templates/components/development-form.hbs
- rails/app/controllers/developments_controller.rb
Apparently key-up events can be unreliable if fired very quickly. When a user enters values very quickly (like a bunch of 0s in quick succession), a key-up event can be missed. In this case, a key-up event being missed means that a value doesn't end up in the proposedChanges even though it is detected by the client-side validations because the value was properly changed.
Resolves #94 which we previously thought was un-reproducable.
Also resolves part of @arouault 's confusion in #183
> Handle null address parts and solve validation form bug

- ember/app/models/user.js
- ember/app/templates/map/developments/development/index.hbs
Resolves #124.
"Importer Bot" is not a user friendly name for a development creator.
Development details list a development's creator as "MAPC Staff" if their email ends in mapc.org.
> Show MAPC users as MAPC Staff

- ember/app/templates/map/developments/development/index.hbs
Resolves #196.
In a multi-million dollar development, decimal places both look silly, and (at first glance) can look like two extra orders of magnitude.
> Remove decimal places from total cost of development

- rails/app/models/development.rb
Resolves #195.
`deleted_at` is a background property for our database administration.
> Exclude deleted_at from downloads

- ember/app/components/mapbox-map.js
- ember/app/services/map.js
Resolves #193.
**IMPORTANT: When reviewing, ensure that #152 remains resolved.**
Filtered developments on page load were being cleared by an unnecessary set call.
This PR removes the unnecessary call and confirms that the call did not actually solve the problem that it was meant to solve. It was originally added in #161 to resolve #152 but it appears we can delete developments off the map without this line now.
> Remove filterData set that was overwriting filtered data

- ember/app/components/mapbox-map.js
Resolves #192.
Switching the map style during editing or creation dropped the orange selector from the map.
The selector and its location is redrawn when a style change occurs, and debouncing variables are cleared.
> Reload selector more carefully when map style changes

- ember/app/styles/modules/table-panel.scss
- ember/app/styles/routes/map/users/verify.scss
- ember/app/templates/map/users/verify.hbs
- rails/app/controllers/users_controller.rb
Resolves #198.
We weren't supposed to be authenticating on user creation (otherwise no one would be able to create users).
This removes the call to authenticate_user. This also restyles the verification panel following the floating panel redesign.
> Restyle verification page and remove blocking authorization

- ember/app/styles/components/search-bar.scss
I broke the width of the searchbar dropdown and this fixes it.
> Fix search bar dropdown

- ember/app/templates/map.hbs
Resolves #120.
I accidentally removed this conditional class while resolving a merge conflict.
I put it back.
> Restore hamburger to X animation

- ember/app/components/share-buttons.js
- ember/app/controllers/map.js
- ember/app/utils/filters.js
Resolves #204 .
The share link serializer was producing an unusable URL.
It fixes the issue by changing the column name that the serializer is looking for.
> Apply column name change for municipal to share link serializer

- ember/app/components/signup-subpanel.js
- ember/app/controllers/map/users/verify.js
- ember/app/styles/components/notifications-popup.scss
- ember/app/styles/components/user-subpanels.scss
- ember/app/styles/routes/map.scss
- ember/app/templates/components/account-subpanel.hbs
- ember/app/templates/components/signup-subpanel.hbs
- ember/app/templates/map/users/verify.hbs
- ember/package-lock.json
- ember/package.json
Resolves #211 .
State and regional users will want the ability to request verified status independent of a specific municipality. Specifically, it's important that they can create developments outside of their home town.
> Allow a user to request verified status independent of a municipality

- ember/app/styles/components/welcome-modal.scss
- ember/app/templates/components/welcome-modal.hbs
Resolves #197 .
The welcome modal content was placeholder text from the FAQ page.
> Update welcome modal content

- rails/app/controllers/developments_controller.rb
Resolves #237.
A regex was used incorrectly causing a failure of all numeric filters on download.
We perform the regex properly.
> Fix incorrect regex use

- rails/config/environments/production.rb
Resolves #242
ActionMailer was not sending emails when we attempted to send password reset emails.
Setting the action_mailer default_url_options which allows ActionMailer to appropriately construct routes using route helpers in production.
Email templates will now use the www.massbuilds.com domain.
> Resolve #242 Fix Action Mailer

- ember/app/components/development-form.js
Resolves #248.
Edits for existing legacy developments with a null summed values (like `hu` or `commsf`) where the summed value was being explicitly changed to 0 would not be validated.
Summed values equal to 0 were being interpreted by an OR statement as falsy and being overwritten with `null`, causing the validation on those summed values to fail.
> Fix validations for summed values equal to 0

- rails/app/models/development.rb
- rails/app/policies/development_policy.rb
Resolves #252.
Municipal users cannot create developments because they development has not been geocoded before it hits the policy guarding the controller.
This PR geocodes within the policy to ensure that municipal users can create developments within their town.
> Geocode in municipal permissions policy for new developments

- rails/config/application.rb
In order to let DataCommon request resources in order for the request from the calendar to work.
> Resolve #280 Add DataCommon to accepted_hosts

- ember/app/styles/components/mapbox-map.scss
The popup fonts were Arial but we wanted it to match the rest of the website. This commit adds the font-family attribute to the mapboxgl popup content class and we now have consistancy.
> Resolve #234 Update Font for Popups

- rails/README.md
- rails/db/seeds.rb
- rails/lib/tasks/db.rake
Since we need our foreign data wrappers to be setup when we run our test suite and development databases, the correct home for it is in seeds.rb where they will be invoked on database creation in all environments. As a result of this improvement we can then remove some setup steps from our README.md.
> Move Database Setup Tasks to Seeds

- ember/app/templates/components/welcome-modal.hbs
Content, it’s fun. We write. We share. Unfortunately our ideas can be bigger than the divs we planned to contain them. Users then lose the ability to close a modal on their iPhones. They cannot see our site. Sad! This fix removes content, for now, to allow most users to access the site. When we have time and resources we can bring this back.
> Resolve #281 Allow Closing Splash on iPhone

- ember/app/routes/map/moderations/index.js
- rails/app/controllers/edits_controller.rb
- rails/spec/factories/edits.rb
- rails/spec/requests/edits_spec.rb
* Instead of always querying all edits we add a parameter that only queries for unapproved edits. This greatly reduces the number of requests made to the server.
* Added note about properly using safe parameters with JSON API fitler param in a get request (which is allowed by the JSON API spec, but apparently not supported by ActiveModelSerializers).
Co-authored-by: Annabelle Thomas Taylor <ataylor@mapc.org>
> Resolve #267 Moderation Overload

- rails/app/policies/development_policy.rb
* Because it is generally not the case that we are providing a record.municipal value when we submit data to the MassBuilds API, we need to use the get_municipality() function to get it. This has the destroy? method mirror the permissions for create? so municipal users can delete their entries.
> Resolve #316 Fix Delete Permissions
